### ISSUE TITLE
Invalid body-key for changeEnvVar

### ISSUE THREAD

**Issue by yusijs** [equinor/radix-api#348]
Im making a wrapper around the radix-api that we plan to use to check statuses programmatically etc in a fast and simple manner. I use code-generation to achieve this, based on the swagger-docs generated for the api. From what I've seen, that radix cli is built in much the same way, generating code based on the swaggerfile. 

Now, the swagger file has a new method documented called `changeEnvVar`, which expects a  body that looks something like this:
```
{
  "environment variable value and metadata": [...]
}
```

While technically valid json, I think this is an oversight and the naming should be more like "environmentVariableValueAndMetadata" (although that's quite the mouthful as well :D).

Relevant section in swagger.json:

```
{
  "description": "New value and metadata",
  "name": "environment variable value and metadata", // here's your problem :) 
  "in": "body",
  "required": true,
  "schema": {
    "type": "array",
    "items": {
      "$ref": "#/definitions/EnvVarParameter"
    }
  }
}
```

I've worked around this in my generator by disabling that specific operation, but a better solution would probably be to fix it in the api :)

**Comment by satr** [comment]
Fixed
